services:
  - type: web
    name: battle-arena-server
    env: node
    region: ohio
    sourceDir: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true
